name: Compress Repository

on:
  push:
    branches:
      - main

jobs:
  compress:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Zip Repository
        run: |
          zip -r repo_archive.zip .
          mv repo_archive.zip ./compressed_repo.zip

      - name: Commit and Push Zip
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add compressed_repo.zip
          git commit -m "Automated repository compression" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git main
